name: Frontend image
on:
  push:

jobs:
  call-image-push:
    uses: DavoA/reusable-workflows/.github/workflows/image-push.yaml@main
    with:
      context: ./frontend
      tags: |
        ${{ secrets.DOCKER_USERNAME }}/app-front:${{ github.sha }}
        ${{ secrets.DOCKER_USERNAME }}/app-front:latest
