name: Frontend image tag change

on:
  workflow_run:
    workflows: [Frontend image push]
    types:
      completed

jobs:
  Using-reusable-cd-workflow:
    uses: DavoA/reusable-workflows/.github/workflows/tag-change.yaml@main
    with:
      image: app-front
      path: back-manifests
      filename: back-deploy.yaml
    secrets:
      dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
      github_pat: ${{ secrets.PAT }}
